import Navbar from "@/src/components/Navbar/Navbar";
import Footer from "@/src/components/Footer/Footer";

import { Fira_Code } from "next/font/google";
import "./normalize.css";
import "./globals.css";

const fira = Fira_Code({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={fira.className}>
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
